version: 2
jobs:
  deploy-develop:
    docker:
      – image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      cloudhubPropertyEnv: Sandbox
      cloudhubWorkerType: MICRO
      cloudhubEnvironment: Sandbox
      cloudhubApplicationName: circle-ci-mulesoft-poc-dev
      logLevel: INFO
    steps:
      – checkout
      – run: 
	      name: Deploy to dev
          command: mvn –s settings.xml deploy -Denv=dev -DcloudhubPropertyCryptKey=${cloudhubPropertyCryptKey} -DmuleDeploy      
	  – save_cache:
		  paths:
		    – ~/.m2
	      key: mvn-cache-circle-ci-mulesoft-poc-dev


workflows:
	version: 2  
	deploy-develop:
		jobs:
		  – deploy-develop:
			  filters:
				branches:
				  only: develop