workflows:
  version: 2  
  dev:
    jobs:
      – deploy_develop:
          filters:
            branches:
              only: develop				  
version: 2
jobs:
  deploy_develop:
    docker:
      – image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      cloudhubPropertyEnv: Sandbox
      cloudhubWorkerType: MICRO
      cloudhubEnvironment: Sandbox
      cloudhubApplicationName: circle-ci-mulesoft-poc-dev
      logLevel: INFO
    steps:
      – run: 
          name: Deploy to dev
          command: mvn –s settings.xml deploy -Denv=dev -DcloudhubPropertyCryptKey=${cloudhubPropertyCryptKey} -DmuleDeploy      
      – save_cache:
          paths:
            – ~/.m2
          key: mvn-cache-circle-ci-mulesoft-poc-dev	